### PR TITLE
Flex backend

### PR DESCRIPTION
**Pull request by alters-mit**
- Removed `folding.py`
- Cleaned up `draping.py`
- 20% of the time, `draping.py` won't add a solid object.
- Added Flex dataset backend (see README) Note that it doesn't yet have fluids implemented.

### CODE REVIEW

**Review by instbldrjems — CHANGES_REQUESTED** [review]
When there is no object being draped, the cloth immediately disappears upon hitting the ground.

**Comment by alters-mit** [comment]
Fixed the issue with the cloth disappearing

**Review by instbldrjems — CHANGES_REQUESTED** [review]
OK so now the cloth has random orientations when draping over objects. It should only have random orientations when it's the cloth alone, i.e. when there is no object to drape over. The draping should have the cloth dropping flat as in the original draping controller. 

Unless we are told otherwise by Dan Bear, that is. But his only comment on the draping and folding videos I posted had to do with the object "shaking", so I think I am correct in this.

**Comment by alters-mit** [comment]
Got it. The cloth now only rotates if there isn't another object.

**Pull request merged**
